name: Auto Multi-Arch Build and Push
run-name: Auto Multi-Arch Build and Push-${{ github.run_started_at }}

on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC时间2点检查一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run sync and build
        run: |
          chmod +x sync_and_build.sh
          ./sync_and_build.sh
