name: Auto Multi-Platform Build and Push

on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨2点检查一次
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache last_tag.txt
        uses: actions/cache@v3
        with:
          path: last_tag.txt
          key: last_tag-${{ github.run_id }}
          restore-keys: |
            last_tag-

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run sync and build
        run: |
          chmod +x sync_and_build.sh
          ./sync_and_build.sh
